version: '3'

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  data: