version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    restart: always
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - data:/home/dynamodblocal/data
    environment:
      - AWS_REGION=eu-west-1
      - DYNAMODB_DATA_PATH=/home/dynamodblocal/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000 || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  data: