version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    restart: always
    container_name: postgres-test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=ralts_cms_test
      - POSTGRES_USER=ralts_user
      - POSTGRES_PASSWORD=ralts_password
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ralts_user -d ralts_cms_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_test_data: 