// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package machine is a generated GoMock package.
package machine

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, machine *Machine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, machine)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, machine interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, machine)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, serialNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, serialNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, serialNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, serialNumber)
}

// GetBySerialNumber mocks base method.
func (m *MockRepository) GetBySerialNumber(ctx context.Context, serialNumber string) (*Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySerialNumber", ctx, serialNumber)
	ret0, _ := ret[0].(*Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySerialNumber indicates an expected call of GetBySerialNumber.
func (mr *MockRepositoryMockRecorder) GetBySerialNumber(ctx, serialNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySerialNumber", reflect.TypeOf((*MockRepository)(nil).GetBySerialNumber), ctx, serialNumber)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, options *ListOptions) ([]*Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, options)
	ret0, _ := ret[0].([]*Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, options)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, machine *Machine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, machine)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, machine interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, machine)
}
