package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"errors"
	"fmt"
	"ralts-cms/graph/model"
	"ralts-cms/internal/machines"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Machines is the resolver for the machines field.
func (r *queryResolver) Machines(ctx context.Context) ([]*model.Machine, error) {
	machines := []*model.Machine{
		{
			SerialNumber: "123-A",
		},
	}

	return machines, nil
}

// MachineForm is the resolver for the machineForm field.
func (r *queryResolver) MachineForm(ctx context.Context, serialNumber *string) (*model.EditForm, error) {
	if serialNumber != nil {
		fields, err := r.MachineResolver.GetFormFieldsBySerialNumber(*serialNumber)
		if err != nil {
			if errors.Is(err, machines.ErrMachineNotFound) {
				return nil, fmt.Errorf("machine with serial number %s not found", *serialNumber)
			}
			return nil, fmt.Errorf("failed to get machine form fields: %w", err)
		}

		return &model.EditForm{Fields: fields}, nil
	}

	return nil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
