// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package maintenance is a generated GoMock package.
package maintenance

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, maintenance *Maintenance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, maintenance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, maintenance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, maintenance)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, machineSerialNumber, workOrderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, machineSerialNumber, workOrderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, machineSerialNumber, workOrderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, machineSerialNumber, workOrderNumber)
}

// GetByWorkOrder mocks base method.
func (m *MockRepository) GetByWorkOrder(ctx context.Context, machineSerialNumber, workOrderNumber string) (*Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWorkOrder", ctx, machineSerialNumber, workOrderNumber)
	ret0, _ := ret[0].(*Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByWorkOrder indicates an expected call of GetByWorkOrder.
func (mr *MockRepositoryMockRecorder) GetByWorkOrder(ctx, machineSerialNumber, workOrderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWorkOrder", reflect.TypeOf((*MockRepository)(nil).GetByWorkOrder), ctx, machineSerialNumber, workOrderNumber)
}

// ListByMachine mocks base method.
func (m *MockRepository) ListByMachine(ctx context.Context, machineSerialNumber string) ([]*Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMachine", ctx, machineSerialNumber)
	ret0, _ := ret[0].([]*Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMachine indicates an expected call of ListByMachine.
func (mr *MockRepositoryMockRecorder) ListByMachine(ctx, machineSerialNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMachine", reflect.TypeOf((*MockRepository)(nil).ListByMachine), ctx, machineSerialNumber)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, maintenance *Maintenance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, maintenance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, maintenance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, maintenance)
}
