// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package maintenance is a generated GoMock package.
package maintenance

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRepository) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder) Count(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository)(nil).Count), ctx)
}

// CountByMachine mocks base method.
func (m *MockRepository) CountByMachine(ctx context.Context, machineSerialNumber string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByMachine", ctx, machineSerialNumber)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByMachine indicates an expected call of CountByMachine.
func (mr *MockRepositoryMockRecorder) CountByMachine(ctx, machineSerialNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByMachine", reflect.TypeOf((*MockRepository)(nil).CountByMachine), ctx, machineSerialNumber)
}

// CountByWorkOrderType mocks base method.
func (m *MockRepository) CountByWorkOrderType(ctx context.Context, machineSerialNumber string) (int, int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByWorkOrderType", ctx, machineSerialNumber)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(int)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// CountByWorkOrderType indicates an expected call of CountByWorkOrderType.
func (mr *MockRepositoryMockRecorder) CountByWorkOrderType(ctx, machineSerialNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByWorkOrderType", reflect.TypeOf((*MockRepository)(nil).CountByWorkOrderType), ctx, machineSerialNumber)
}

// CountSearchByMachine mocks base method.
func (m *MockRepository) CountSearchByMachine(ctx context.Context, machineSerialNumber, query string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSearchByMachine", ctx, machineSerialNumber, query)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSearchByMachine indicates an expected call of CountSearchByMachine.
func (mr *MockRepositoryMockRecorder) CountSearchByMachine(ctx, machineSerialNumber, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSearchByMachine", reflect.TypeOf((*MockRepository)(nil).CountSearchByMachine), ctx, machineSerialNumber, query)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, maintenance *Maintenance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, maintenance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, maintenance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, maintenance)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, machineSerialNumber, workOrderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, machineSerialNumber, workOrderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, machineSerialNumber, workOrderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, machineSerialNumber, workOrderNumber)
}

// GetByWorkOrder mocks base method.
func (m *MockRepository) GetByWorkOrder(ctx context.Context, machineSerialNumber, workOrderNumber string) (*Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWorkOrder", ctx, machineSerialNumber, workOrderNumber)
	ret0, _ := ret[0].(*Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByWorkOrder indicates an expected call of GetByWorkOrder.
func (mr *MockRepositoryMockRecorder) GetByWorkOrder(ctx, machineSerialNumber, workOrderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWorkOrder", reflect.TypeOf((*MockRepository)(nil).GetByWorkOrder), ctx, machineSerialNumber, workOrderNumber)
}

// ListByMachine mocks base method.
func (m *MockRepository) ListByMachine(ctx context.Context, machineSerialNumber string, options *ListOptions) ([]*Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMachine", ctx, machineSerialNumber, options)
	ret0, _ := ret[0].([]*Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMachine indicates an expected call of ListByMachine.
func (mr *MockRepositoryMockRecorder) ListByMachine(ctx, machineSerialNumber, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMachine", reflect.TypeOf((*MockRepository)(nil).ListByMachine), ctx, machineSerialNumber, options)
}

// SearchByMachine mocks base method.
func (m *MockRepository) SearchByMachine(ctx context.Context, machineSerialNumber, query string, options *ListOptions) ([]*Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByMachine", ctx, machineSerialNumber, query, options)
	ret0, _ := ret[0].([]*Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByMachine indicates an expected call of SearchByMachine.
func (mr *MockRepositoryMockRecorder) SearchByMachine(ctx, machineSerialNumber, query, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByMachine", reflect.TypeOf((*MockRepository)(nil).SearchByMachine), ctx, machineSerialNumber, query, options)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, maintenance *Maintenance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, maintenance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, maintenance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, maintenance)
}
