// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notifications/service.go

// Package notifications is a generated GoMock package.
package notifications

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockService) Notify(ctx context.Context, n Notification) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify", ctx, n)
}

// Notify indicates an expected call of Notify.
func (mr *MockServiceMockRecorder) Notify(ctx, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockService)(nil).Notify), ctx, n)
}
