// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notifications/repository.go

// Package notifications is a generated GoMock package.
package notifications

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountForUser mocks base method.
func (m *MockRepository) CountForUser(ctx context.Context, userID int64, opts ListOptions) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountForUser", ctx, userID, opts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountForUser indicates an expected call of CountForUser.
func (mr *MockRepositoryMockRecorder) CountForUser(ctx, userID, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountForUser", reflect.TypeOf((*MockRepository)(nil).CountForUser), ctx, userID, opts)
}

// CountUnread mocks base method.
func (m *MockRepository) CountUnread(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnread", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnread indicates an expected call of CountUnread.
func (mr *MockRepositoryMockRecorder) CountUnread(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnread", reflect.TypeOf((*MockRepository)(nil).CountUnread), ctx, userID)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, n *Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, n)
}

// ListForUser mocks base method.
func (m *MockRepository) ListForUser(ctx context.Context, userID int64, opts ListOptions) ([]*Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForUser", ctx, userID, opts)
	ret0, _ := ret[0].([]*Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForUser indicates an expected call of ListForUser.
func (mr *MockRepositoryMockRecorder) ListForUser(ctx, userID, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForUser", reflect.TypeOf((*MockRepository)(nil).ListForUser), ctx, userID, opts)
}

// MarkAllRead mocks base method.
func (m *MockRepository) MarkAllRead(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllRead", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkAllRead indicates an expected call of MarkAllRead.
func (mr *MockRepositoryMockRecorder) MarkAllRead(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllRead", reflect.TypeOf((*MockRepository)(nil).MarkAllRead), ctx, userID)
}

// MarkRead mocks base method.
func (m *MockRepository) MarkRead(ctx context.Context, userID int64, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockRepositoryMockRecorder) MarkRead(ctx, userID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockRepository)(nil).MarkRead), ctx, userID, id)
}
