// Code generated by MockGen. DO NOT EDIT.
// Source: attachment.go

// Package attachments is a generated GoMock package.
package attachments

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAttachmentService is a mock of AttachmentService interface.
type MockAttachmentService struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentServiceMockRecorder
}

// MockAttachmentServiceMockRecorder is the mock recorder for MockAttachmentService.
type MockAttachmentServiceMockRecorder struct {
	mock *MockAttachmentService
}

// NewMockAttachmentService creates a new mock instance.
func NewMockAttachmentService(ctrl *gomock.Controller) *MockAttachmentService {
	mock := &MockAttachmentService{ctrl: ctrl}
	mock.recorder = &MockAttachmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentService) EXPECT() *MockAttachmentServiceMockRecorder {
	return m.recorder
}

// CreateMachineAttachment mocks base method.
func (m *MockAttachmentService) CreateMachineAttachment(ctx context.Context, machineSerialNumber, attachmentName string, data []byte, contentType string) (*Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMachineAttachment", ctx, machineSerialNumber, attachmentName, data, contentType)
	ret0, _ := ret[0].(*Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMachineAttachment indicates an expected call of CreateMachineAttachment.
func (mr *MockAttachmentServiceMockRecorder) CreateMachineAttachment(ctx, machineSerialNumber, attachmentName, data, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMachineAttachment", reflect.TypeOf((*MockAttachmentService)(nil).CreateMachineAttachment), ctx, machineSerialNumber, attachmentName, data, contentType)
}

// CreateMaintenanceAttachment mocks base method.
func (m *MockAttachmentService) CreateMaintenanceAttachment(ctx context.Context, machineSerialNumber, workOrderNumber, attachmentName string, data []byte, contentType string) (*Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMaintenanceAttachment", ctx, machineSerialNumber, workOrderNumber, attachmentName, data, contentType)
	ret0, _ := ret[0].(*Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMaintenanceAttachment indicates an expected call of CreateMaintenanceAttachment.
func (mr *MockAttachmentServiceMockRecorder) CreateMaintenanceAttachment(ctx, machineSerialNumber, workOrderNumber, attachmentName, data, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMaintenanceAttachment", reflect.TypeOf((*MockAttachmentService)(nil).CreateMaintenanceAttachment), ctx, machineSerialNumber, workOrderNumber, attachmentName, data, contentType)
}

// DeleteMachineAttachment mocks base method.
func (m *MockAttachmentService) DeleteMachineAttachment(ctx context.Context, machineSerialNumber, attachmentName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMachineAttachment", ctx, machineSerialNumber, attachmentName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMachineAttachment indicates an expected call of DeleteMachineAttachment.
func (mr *MockAttachmentServiceMockRecorder) DeleteMachineAttachment(ctx, machineSerialNumber, attachmentName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMachineAttachment", reflect.TypeOf((*MockAttachmentService)(nil).DeleteMachineAttachment), ctx, machineSerialNumber, attachmentName)
}

// DeleteMaintenanceAttachment mocks base method.
func (m *MockAttachmentService) DeleteMaintenanceAttachment(ctx context.Context, machineSerialNumber, workOrderNumber, attachmentName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMaintenanceAttachment", ctx, machineSerialNumber, workOrderNumber, attachmentName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMaintenanceAttachment indicates an expected call of DeleteMaintenanceAttachment.
func (mr *MockAttachmentServiceMockRecorder) DeleteMaintenanceAttachment(ctx, machineSerialNumber, workOrderNumber, attachmentName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMaintenanceAttachment", reflect.TypeOf((*MockAttachmentService)(nil).DeleteMaintenanceAttachment), ctx, machineSerialNumber, workOrderNumber, attachmentName)
}

// GetMachineAttachment mocks base method.
func (m *MockAttachmentService) GetMachineAttachment(ctx context.Context, machineSerialNumber, attachmentName string) (*Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineAttachment", ctx, machineSerialNumber, attachmentName)
	ret0, _ := ret[0].(*Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineAttachment indicates an expected call of GetMachineAttachment.
func (mr *MockAttachmentServiceMockRecorder) GetMachineAttachment(ctx, machineSerialNumber, attachmentName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineAttachment", reflect.TypeOf((*MockAttachmentService)(nil).GetMachineAttachment), ctx, machineSerialNumber, attachmentName)
}

// GetMaintenanceAttachment mocks base method.
func (m *MockAttachmentService) GetMaintenanceAttachment(ctx context.Context, machineSerialNumber, workOrderNumber, attachmentName string) (*Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaintenanceAttachment", ctx, machineSerialNumber, workOrderNumber, attachmentName)
	ret0, _ := ret[0].(*Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaintenanceAttachment indicates an expected call of GetMaintenanceAttachment.
func (mr *MockAttachmentServiceMockRecorder) GetMaintenanceAttachment(ctx, machineSerialNumber, workOrderNumber, attachmentName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaintenanceAttachment", reflect.TypeOf((*MockAttachmentService)(nil).GetMaintenanceAttachment), ctx, machineSerialNumber, workOrderNumber, attachmentName)
}

// MockAttachmentRepository is a mock of AttachmentRepository interface.
type MockAttachmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentRepositoryMockRecorder
}

// MockAttachmentRepositoryMockRecorder is the mock recorder for MockAttachmentRepository.
type MockAttachmentRepositoryMockRecorder struct {
	mock *MockAttachmentRepository
}

// NewMockAttachmentRepository creates a new mock instance.
func NewMockAttachmentRepository(ctrl *gomock.Controller) *MockAttachmentRepository {
	mock := &MockAttachmentRepository{ctrl: ctrl}
	mock.recorder = &MockAttachmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentRepository) EXPECT() *MockAttachmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAttachmentRepository) Create(ctx context.Context, attachment *Attachment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, attachment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAttachmentRepositoryMockRecorder) Create(ctx, attachment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAttachmentRepository)(nil).Create), ctx, attachment)
}

// Delete mocks base method.
func (m *MockAttachmentRepository) Delete(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAttachmentRepositoryMockRecorder) Delete(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAttachmentRepository)(nil).Delete), ctx, name)
}

// Get mocks base method.
func (m *MockAttachmentRepository) Get(ctx context.Context, name string) (*Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAttachmentRepositoryMockRecorder) Get(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAttachmentRepository)(nil).Get), ctx, name)
}
