// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type EditForm struct {
	Fields []*FormField `json:"fields"`
}

type FormField struct {
	Type  FormFieldType `json:"type"`
	Label string        `json:"label"`
	Value string        `json:"value"`
}

type Machine struct {
	SerialNumber string `json:"serialNumber"`
	Customer     string `json:"customer"`
	AccountType  string `json:"accountType"`
	ReportedBy   string `json:"reportedBy"`
	PpmDate      string `json:"ppmDate"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID        string `json:"id"`
	Text      string `json:"text"`
	Done      bool   `json:"done"`
	User      *User  `json:"user"`
	CreatedAt int    `json:"createdAt"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type FormFieldType string

const (
	FormFieldTypeText     FormFieldType = "TEXT"
	FormFieldTypeRadio    FormFieldType = "RADIO"
	FormFieldTypeCalendar FormFieldType = "CALENDAR"
)

var AllFormFieldType = []FormFieldType{
	FormFieldTypeText,
	FormFieldTypeRadio,
	FormFieldTypeCalendar,
}

func (e FormFieldType) IsValid() bool {
	switch e {
	case FormFieldTypeText, FormFieldTypeRadio, FormFieldTypeCalendar:
		return true
	}
	return false
}

func (e FormFieldType) String() string {
	return string(e)
}

func (e *FormFieldType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FormFieldType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FormFieldType", str)
	}
	return nil
}

func (e FormFieldType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
