// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package flags is a generated GoMock package.
package flags

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRepository) Count(ctx context.Context, opts ListOptions) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, opts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder) Count(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository)(nil).Count), ctx, opts)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, f *Flag) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, f)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, f)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id string) (*Flag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*Flag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, opts ListOptions) ([]*Flag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*Flag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, opts)
}

// ListForMachine mocks base method.
func (m *MockRepository) ListForMachine(ctx context.Context, serialNumber string, includeResolved bool) ([]*Flag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForMachine", ctx, serialNumber, includeResolved)
	ret0, _ := ret[0].([]*Flag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForMachine indicates an expected call of ListForMachine.
func (mr *MockRepositoryMockRecorder) ListForMachine(ctx, serialNumber, includeResolved interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForMachine", reflect.TypeOf((*MockRepository)(nil).ListForMachine), ctx, serialNumber, includeResolved)
}

// ListOpenBySerials mocks base method.
func (m *MockRepository) ListOpenBySerials(ctx context.Context, serialNumbers []string) (map[string][]*Flag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpenBySerials", ctx, serialNumbers)
	ret0, _ := ret[0].(map[string][]*Flag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOpenBySerials indicates an expected call of ListOpenBySerials.
func (mr *MockRepositoryMockRecorder) ListOpenBySerials(ctx, serialNumbers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpenBySerials", reflect.TypeOf((*MockRepository)(nil).ListOpenBySerials), ctx, serialNumbers)
}

// Resolve mocks base method.
func (m *MockRepository) Resolve(ctx context.Context, id string, resolvedBy int64, resolutionNote string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, id, resolvedBy, resolutionNote)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockRepositoryMockRecorder) Resolve(ctx, id, resolvedBy, resolutionNote interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockRepository)(nil).Resolve), ctx, id, resolvedBy, resolutionNote)
}
