// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package flags is a generated GoMock package.
package flags

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CanResolve mocks base method.
func (m *MockService) CanResolve(ctx context.Context, userID int64, isAdmin bool, flagID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanResolve", ctx, userID, isAdmin, flagID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanResolve indicates an expected call of CanResolve.
func (mr *MockServiceMockRecorder) CanResolve(ctx, userID, isAdmin, flagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanResolve", reflect.TypeOf((*MockService)(nil).CanResolve), ctx, userID, isAdmin, flagID)
}

// CreateManualFlag mocks base method.
func (m *MockService) CreateManualFlag(ctx context.Context, actorUserID int64, serialNumber string, reason Reason, note string) (*Flag, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManualFlag", ctx, actorUserID, serialNumber, reason, note)
	ret0, _ := ret[0].(*Flag)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateManualFlag indicates an expected call of CreateManualFlag.
func (mr *MockServiceMockRecorder) CreateManualFlag(ctx, actorUserID, serialNumber, reason, note interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManualFlag", reflect.TypeOf((*MockService)(nil).CreateManualFlag), ctx, actorUserID, serialNumber, reason, note)
}

// Resolve mocks base method.
func (m *MockService) Resolve(ctx context.Context, actorUserID int64, isAdmin bool, id, resolutionNote string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, actorUserID, isAdmin, id, resolutionNote)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockServiceMockRecorder) Resolve(ctx, actorUserID, isAdmin, id, resolutionNote interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockService)(nil).Resolve), ctx, actorUserID, isAdmin, id, resolutionNote)
}
