[variables]
NODE_VERSION = "20"
HOSTNAME = "0.0.0.0"
PORT = "8080"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci --no-audit --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
