[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci --no-audit"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .next/standalone/server.js"
